In [1]:
from __future__ import print_function
import torch

In [ ]:
x=torch.empty(5,3)
print(x)

In [24]:
x = torch.rand(5,3)
print(x)

tensor([[0.9049, 0.8942, 0.7127],
        [0.6272, 0.2494, 0.3146],
        [0.1370, 0.8881, 0.5072],
        [0.8618, 0.7678, 0.0656],
        [0.7478, 0.7374, 0.6935]])


In [9]:
x=torch.zeros(5,3,dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [17]:
x=torch.tensor([5,3])
print(x.dtype)

torch.int64


In [16]:
x = x.new_ones(5,3)
print(x.dtype)


torch.int64


In [20]:
print(torch.Size(x))

torch.Size([5, 3])


In [21]:
y = torch.randn(5,3)

In [27]:
result = torch.empty(5,3)
torch.add(x,y,out = result)
print(result)

tensor([[ 2.1505,  1.5898, -1.6424],
        [-0.4299, -0.3689, -0.8002],
        [ 0.7829,  1.0278,  0.9187],
        [ 0.5312,  0.8366, -1.0235],
        [ 0.8901,  2.2645,  0.8545]])


In [28]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [31]:
x = torch.randn(1)
print(x)
x.item()

tensor([0.2395])


0.23946793377399445

In [36]:
a = torch.ones(1)
b = a.add_(1)
c = a.numpy()
d = b.add_(2)
print(a,b,c)

tensor([4.]) tensor([4.]) [4.]


In [38]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a,b)

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [43]:
## Autograd
x = torch.ones(2,2,requires_grad= True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [44]:
y =2*x
print(y)

tensor([[2., 2.],
        [2., 2.]], grad_fn=<MulBackward0>)


In [45]:
y = 2+x
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [47]:
print(y.grad_fn)

In [48]:
z = y*y*3
z = z.mean()
print(z)

tensor(27., grad_fn=<MeanBackward1>)


In [53]:
#z.backward()
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [54]:
x = torch.randn(3,requires_grad = True)
y = x*2
while y.data.norm()<1000:
    y = y*2
print(y)

tensor([  652.3127,    86.6054, -1888.1228], grad_fn=<MulBackward0>)


In [57]:
v = torch.randn(3,requires_grad = True)
y.backward(v)
print(x.grad)

tensor([-230.2880, -398.0993, -437.0096])


In [61]:
print(x.requires_grad)
with torch.no_grad():
    print((x**2).requires_grad)

True
False
